import { Button } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import Layout from "~/layouts/layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Real Estate NFT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Button>Text</Button>
        </Layout>
      </main>
    </>
  );
};

export default Home;
