import { Grid } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import RealEstateCard from "~/components/RealEstateCard";
import { graphql } from "~/gql";
import { useGraphQL } from "~/hooks/useGraphql";
import Layout from "~/layouts/layout";

const nftModelsDocument = graphql(/* GraphQL */ `
  query nftModels($appId: ID) {
    nftModels(appId: $appId) {
      items {
        id
        blockchainId
        title
        description
        quantity
        status
        rarity
        content {
          files {
            url
            contentType
          }
          poster {
            url
          }
        }
      }
      cursor
    }
  }
`);

const Home: NextPage = () => {
  const { data, isLoading } = useGraphQL(
    nftModelsDocument,
    {},
    {
      appId: process.env.NEXT_PUBLIC_CLIENT_ID,
    }
  );
  return (
    <>
      <Head>
        <title>Real Estate NFT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          {!isLoading && (
            <Grid>
              {data?.nftModels?.items?.map((item) => (
                <Grid.Col key={item?.id as string} span={3}>
                  <RealEstateCard
                    id={item?.id as string}
                    description={item?.description as string}
                    image={item?.content?.poster?.url}
                    price={100}
                    title={item?.title as string}
                  />
                </Grid.Col>
              ))}
            </Grid>
          )}
        </Layout>
      </main>
    </>
  );
};

export default Home;
